arjuns_birthday=input("arjuns birthdate: ")
print(arjuns_birthday)
anands_birthday=input("anands birthdate: ")
print(anands_birthday)
ashwinis_birthday=input("ashwinis birthdate: ")
print(ashwinis_birthday)
aditis_birthday=input("aditis birthdate: ")
print(aditis_birthday)
ashoks_birthday=input("ashoks birthdate: ")
print(ashoks_birthday)
